//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth.Phone.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OAuth.Phone.Utils.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истек срок действия кода.
        /// </summary>
        public static string AuthenticationCodeExpired {
            get {
                return ResourceManager.GetString("AuthenticationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код авторизации не найден или уже был использован.
        /// </summary>
        public static string AuthenticationCodeNotFoundOrWasUsed {
            get {
                return ResourceManager.GetString("AuthenticationCodeNotFoundOrWasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышено количество неправильного ввода кода.
        /// </summary>
        public static string ConfirmationCodeErrorsExceeded {
            get {
                return ResourceManager.GetString("ConfirmationCodeErrorsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истек срок действия кода.
        /// </summary>
        public static string ConfirmationCodeExpired {
            get {
                return ResourceManager.GetString("ConfirmationCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный код подтверждения.
        /// </summary>
        public static string ConfirmationCodeIncorrect {
            get {
                return ResourceManager.GetString("ConfirmationCodeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка невозможна. Необходимо подождать.
        /// </summary>
        public static string ConfirmationCodeSendWait {
            get {
                return ResourceManager.GetString("ConfirmationCodeSendWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный пераметр запроса.
        /// </summary>
        public static string InvalidParam {
            get {
                return ResourceManager.GetString("InvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный пераметр запроса &quot;{0}&quot;.
        /// </summary>
        public static string InvalidParamFormat {
            get {
                return ResourceManager.GetString("InvalidParamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер не найден.
        /// </summary>
        public static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенаправление на указанный адрес недопустимо.
        /// </summary>
        public static string RedirectrUrlInvalid {
            get {
                return ResourceManager.GetString("RedirectrUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует адрес для перенаправления.
        /// </summary>
        public static string RedirectUrlMissing {
            get {
                return ResourceManager.GetString("RedirectUrlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь заблокирован.
        /// </summary>
        public static string UserIsDisabled {
            get {
                return ResourceManager.GetString("UserIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
